# Generated by Django 4.2.7 on 2023-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Mobilephone', 'Mobilephone'), ('Tablet', 'Tablet'), ('Smartwatch', 'Smartwatch'), ('Laptop', 'Laptop')], default='Mobilephone', max_length=100),
        ),
    ]
